"""Regression tests for the in-container body generated by run_scripts/mpc_server.sh.

The failure these encode:

    /home/akn7847/.ts_mpc_body.sh: line 7: ENV_FILE: unbound variable

The wrapper wrote the body heredoc first and appended the `export VALUE=...` preamble to
the *end* of the generated file -- i.e. after the body's `exit "$rc"`, so it never ran. The
body runs under `set -u`, so its first variable reference aborted the job inside the
container, after a queue slot had been spent.

Test 1 re-implements the ordering check in Python, independently of the bash guard inside
the wrapper, and requires the real generated body to be clean; test 2 requires the
historical layout to be caught (so the checker cannot rot); test 3 runs the committed
end-to-end self-test (stub apptainer, stub conda, stub run_mpc.sh).

Run with either:
    python tests/test_mpc_body.py
    pytest tests/test_mpc_body.py        # from the repo root (ts env)
"""

import os
import pathlib
import re
import subprocess

import pytest

REPO = pathlib.Path(__file__).resolve().parents[1]
WRAPPER = REPO / "run_scripts" / "mpc_server.sh"
SELFTEST = REPO / "run_scripts" / "selftest_mpc_server.sh"

# What the shell itself provides, plus DATA_ROOT (exported by dataset_paths.sh, which the
# body sources inside the container).
SHELL_PROVIDED = {"HOME", "PWD", "PATH", "USER", "SHLVL", "IFS", "HOSTNAME", "LINENO",
                  "TERM", "LANG", "DATA_ROOT", "PYTHON"}
ASSIGN = re.compile(r"(?:^|[\s;])(?:export\s+|local\s+)?(\w+)[=+]")
FOR_IN = re.compile(r"\bfor\s+(\w+)\s+in\b")
USE = re.compile(r"\$\{?(\w+)")


def use_before_definition(body):
    """[(line, name), ...] for every variable used before it is defined."""
    defined, bad = set(SHELL_PROVIDED), []
    for n, line in enumerate(body.splitlines(), 1):
        if line.lstrip().startswith("#"):
            continue
        for m in ASSIGN.finditer(line):          # a same-line assignment counts for that line
            defined.add(m.group(1))
        for m in FOR_IN.finditer(line):
            defined.add(m.group(1))
        for m in USE.finditer(line):
            if m.group(1) not in defined:
                bad.append((n, m.group(1)))
    return bad


def preamble_names():
    """The single source of truth inside the wrapper, used here to check completeness."""
    m = re.search(r"PREAMBLE_VARS=\((.*?)\)", WRAPPER.read_text(), re.S)
    assert m, "PREAMBLE_VARS not found in mpc_server.sh"
    return m.group(1).split()


def generated_body(tmp_path):
    """Run the wrapper in DRY_RUN (which lints the body) and return what it wrote."""
    (tmp_path / "ck" / "test").mkdir(parents=True)
    for stub in ("sif", "ovl", "env.sh"):
        (tmp_path / stub).write_text("")
    env = dict(os.environ,
               SLURM_SUBMIT_DIR=str(REPO),
               # Say explicitly where the checkout is *and* that it is visible inside the
               # simulated container: the wrapper refuses an out-of-$HOME checkout unless
               # told, and this test must work from a /tmp clone as well as under $HOME.
               REPO_HOST=str(REPO),
               REPO_IN_CONTAINER=str(REPO),
               ALLOW_OUTSIDE_HOME="1",
               BODY=str(tmp_path / "body.sh"),
               CKPT_ROOT=str(tmp_path / "ck"),
               CKBPT=str(tmp_path / "ck" / "test"),
               SIF=str(tmp_path / "sif"),
               OVERLAY=str(tmp_path / "ovl"),
               ENV_FILE=str(tmp_path / "env.sh"),
               DRY_RUN="1", PREFLIGHT="0")
    result = subprocess.run(["bash", str(WRAPPER), "umaze", "all", "gd_mpc"],
                            cwd=str(REPO), env=env, capture_output=True, text=True)
    # the wrapper refuses to go on if its own guard objects, so this is the first assertion
    assert result.returncode == 0, result.stdout + result.stderr
    return (tmp_path / "body.sh").read_text()


def test_generated_body_defines_every_value_before_using_it(tmp_path):
    body = generated_body(tmp_path)
    assert use_before_definition(body) == [], "the body uses a value before defining it"

    lines = body.splitlines()
    assert lines[0].startswith("#!")
    assert lines[2] == "set -uo pipefail"
    assert lines[3].startswith("export REPO_IN_CONTAINER="), "the preamble must come first"
    assert 'exit "$rc"' in body, "the body must still end by reporting failure"

    for name in preamble_names():
        assert re.search(r"^export %s=" % name, body, re.M), "%s is not exported" % name


def test_checker_catches_the_layout_that_broke_the_server(tmp_path):
    """Preamble moved to the end -- exactly what shipped, and must never pass again."""
    body = generated_body(tmp_path)
    text = body.splitlines(True)
    exports = [l for l in text if l.startswith("export ") and "$(printf" not in l]
    broken = "".join([l for l in text if l not in exports] + exports)

    bad = use_before_definition(broken)
    assert bad, "the historical layout must be flagged"
    assert "ENV_FILE" in {name for _, name in bad}

    # and the reason it matters: bash -u really does abort on it
    proc = subprocess.run(["bash", "-c", 'set -u' + os.linesep + '[ -r "$ENV_FILE" ]'],
                          capture_output=True, text=True)
    assert proc.returncode != 0
    assert "unbound variable" in proc.stderr


def test_shipped_selftest_passes():
    """The end-to-end self-test that the user can also run on the login node."""
    result = subprocess.run(["bash", str(SELFTEST)], cwd=str(REPO),
                            capture_output=True, text=True)
    assert result.returncode == 0, result.stdout + result.stderr
    assert "0 failed" in result.stdout


if __name__ == "__main__":
    raise SystemExit(pytest.main([__file__, "-q"]))
