#!/bin/bash
# =============================================================================
# mpc_server.sh -- sbatch-able wrapper that runs run_mpc.sh (planning / MPC) inside
#                  the project container on one GPU node.
#
#   sbatch run_scripts/mpc_server.sh                       # default JOBS (3 envs x gd_mpc, all arms)
#   sbatch run_scripts/mpc_server.sh umaze all both        # one job: env variant planner
#   FULL=0 sbatch run_scripts/mpc_server.sh                # validation: OOM check + runtime estimate
#   OL=1   sbatch run_scripts/mpc_server.sh                # open loop (one plan per episode)
#   SEEDS="100" PREFLIGHT=0 OVERLAY_RW=1 sbatch ...        # knobs (see below)
#   JOBS="umaze:all:gd_mpc medium:both:both" sbatch ...    # explicit grid
#
# Inside one allocation the jobs run SEQUENTIALLY -- planning wants the whole GPU --
# each into $CKPT_ROOT/logs/mpc_<env>_<variant>_<planner>.log, then a pass/fail summary.
#
# Arm names: run_mpc.sh's built-in MODELS are the dev machine's names. The checkpoints
# trained here use different recipes (projchannel, ttaggtwothirds, aggflatten), so
# run_mpc.sh DISCOVERS the four arms under $CKPT_ROOT/test by token (baseline=_False_,
# straighten=cos without two-thirds, p_reg=two-thirds without cos, both=cos+two-thirds)
# whenever the built-ins are absent, and aborts with the candidate list if an arm is
# ambiguous. ARM_NAMES="..." still wins, and is then used for every job in the grid.
#
# Preflight (PREFLIGHT=1, the default) runs run_scripts/mujoco_smoke.py in the same
# container first, so a broken simulator/dataset/EGL fails in seconds instead of after
# plan.py's startup. The first run of a *new* machine may also want OVERLAY_RW=1 (the
# first import of mujoco_py compiles cymj into the overlay); afterwards read-only is
# enough and can share the node with a training job.
#
# Edit the #SBATCH lines for your account/partition if they differ.
# =============================================================================
#SBATCH --job-name=ts-mpc
#SBATCH --account=torch_pr_718_cds
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=8
#SBATCH --mem=128G
#SBATCH --time=24:00:00
#SBATCH --output=/scratch/akn7847/datasets/worldmodelcheckpoints/logs/slurm-mpc-%j.out
#SBATCH --error=/scratch/akn7847/datasets/worldmodelcheckpoints/logs/slurm-mpc-%j.err
set -euo pipefail

REPO_HOST="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SIF="${SIF:-/share/apps/images/cuda12.1.1-cudnn8.9.0-devel-ubuntu22.04.2.sif}"
OVERLAY="${OVERLAY:-/scratch/akn7847/containers/temporal-straightening/overlay-50G-10M.ext3}"
REPO_IN_CONTAINER="${REPO_IN_CONTAINER:-/home/akn7847/wm/temporal-straightening-PL}"
BODY="${BODY:-$HOME/.ts_mpc_body.sh}"
# shared data/checkpoint layout, same file train_server.sh uses
source "$REPO_HOST/run_scripts/dataset_paths.sh"

FULL="${FULL:-1}"
OL="${OL:-0}"
SEEDS="${SEEDS:-100 101 102}"
PREFLIGHT="${PREFLIGHT:-1}"
CKBPT_PATH="${CKBPT:-$CKPT_ROOT/test}"
MOUNT="$OVERLAY:ro"; [ "${OVERLAY_RW:-0}" = "1" ] && MOUNT="$OVERLAY"
if [ "$#" -ge 2 ]; then
    JOBS="$1:$2:${3:-both}"
else
    JOBS="${JOBS:-umaze:all:gd_mpc medium:all:gd_mpc pusht:all:gd_mpc}"
fi

for arg in "$@"; do case "$arg" in -h|--help) sed -n '2,32p' "$0"; exit 0 ;; esac; done

if ! mkdir -p "$CKPT_ROOT/logs" 2>/dev/null; then
    echo "FATAL: cannot create $CKPT_ROOT/logs -- is CKPT_ROOT (=$CKPT_ROOT) correct for this machine?" >&2
    exit 1
fi
echo "==================== $(date '+%F %H:%M:%S') ===================="
echo "host=$(hostname) job=${SLURM_JOB_ID:-local} gpu=$(nvidia-smi -L 2>/dev/null | head -1)"
echo "jobs    : $JOBS"
echo "mode    : FULL=$FULL OL=$OL seeds='$SEEDS' preflight=$PREFLIGHT overlay=$MOUNT"
echo "ckpt    : $CKBPT_PATH"
echo "data    : DATA_ROOT=$DATA_ROOT"
[ -f "$SIF" ] || { echo "FATAL: container image not found: $SIF" >&2; exit 1; }
[ -f "$OVERLAY" ] || { echo "FATAL: overlay not found: $OVERLAY" >&2; exit 1; }
[ -d "$CKBPT_PATH" ] || { echo "FATAL: checkpoint dir not found: $CKBPT_PATH (CKPT_ROOT/test)" >&2; exit 1; }

# ---- the in-container body (kept in a generated file so its quoting is verifiable) ----
cat > "$BODY" <<'BODYEOF'
#!/usr/bin/env bash
# Generated by run_scripts/mpc_server.sh. Values are exported just below.
set -uo pipefail
export PATH=/opt/miniconda/bin:$PATH
source /opt/miniconda/etc/profile.d/conda.sh
conda activate ts
[ -r "$ENV_FILE" ] || { echo "FATAL: $ENV_FILE not visible in the container -- add --bind \$HOME:\$HOME" >&2; exit 9; }
source "$ENV_FILE"
cd "$REPO_IN_CONTAINER"
source run_scripts/dataset_paths.sh
export PYTHONPATH="$PWD${PYTHONPATH:+:$PYTHONPATH}"
log_dir="$CKPT_ROOT/logs"
mkdir -p "$log_dir"
echo "[container] python=$(command -v python)  DATA_ROOT=$DATA_ROOT  log_dir=$log_dir"

if [ "$PREFLIGHT" = "1" ]; then
    echo "---- preflight: mujoco / gym / EGL / datasets ----"
    python run_scripts/mujoco_smoke.py || {
        echo "FATAL: preflight failed -- not starting plan.py (fix the stage above)." >&2
        exit 1
    }
fi

rc=0
fail=""
for job in $JOBS; do
    env_sel="${job%%:*}"; rest="${job#*:}"
    variant="${rest%%:*}"; planner="${rest#*:}"
    log="$log_dir/mpc_${env_sel}_${variant}_${planner}.log"
    echo
echo "---- $(date '+%F %H:%M:%S') $env_sel / $variant / $planner -> $log ----"
    if FULL="$FULL" OL="$OL" SEEDS="$SEEDS" \
       bash run_scripts/run_mpc.sh "$env_sel" "$variant" "$planner" --ckpt "$CKBPT_PATH" 2>&1 | tee -a "$log"; then
        echo "  [ok]   $env_sel $variant $planner"
    else
        echo "  [FAIL] $env_sel $variant $planner  (see $log)" >&2
        fail="$fail $env_sel/$variant/$planner"
        rc=1
    fi
done

echo
echo "==================== summary ===================="
for job in $JOBS; do
    env_sel="${job%%:*}"; rest="${job#*:}"
    variant="${rest%%:*}"; planner="${rest#*:}"
    log="$log_dir/mpc_${env_sel}_${variant}_${planner}.log"
    sr=$(grep -oE 'success_rate[ =:]+[0-9.]+' "$log" 2>/dev/null | tail -1 | grep -oE '[0-9.]+' || true)
    printf '  %-28s %-9s %-8s success_rate=%s\n' "$env_sel" "$variant" "$planner" "${sr:-<n/a>}"
    echo "      log: $log"
done
[ -n "$fail" ] && echo "failed:$fail"
echo "summaries: $REPO_IN_CONTAINER/plan_outputs_*/summaries/"
exit "$rc"
BODYEOF

{ echo "export REPO_IN_CONTAINER=$(printf '%q' "$REPO_IN_CONTAINER")"
  echo "export FULL=$(printf '%q' "$FULL") OL=$(printf '%q' "$OL") SEEDS=$(printf '%q' "$SEEDS")"
  echo "export PREFLIGHT=$(printf '%q' "$PREFLIGHT") JOBS=$(printf '%q' "$JOBS")"
  echo "export CKBPT_PATH=$(printf '%q' "$CKBPT_PATH") CKPT_ROOT=$(printf '%q' "$CKPT_ROOT")"
  echo "export ENV_FILE=$(printf '%q' "${ENV_FILE:-$HOME/mujoco_env.sh}")"
} >> "$BODY"
chmod +x "$BODY"

if [ "${DRY_RUN:-0}" = "1" ]; then
    echo "--dry-run: apptainer exec --fakeroot --nv --bind \$HOME:\$HOME --overlay $MOUNT $SIF bash -lc 'bash $BODY'"
    echo "---- generated body ----"
    sed -n '1,200p' "$BODY"
    exit 0
fi

echo "body: $BODY   (container: $SIF)"
apptainer exec --fakeroot --nv --bind "$HOME:$HOME" --overlay "$MOUNT" "$SIF" \
    bash -lc "bash $BODY"
