#!/usr/bin/env bash
# =============================================================================
# setup_mujoco_server.sh -- bring the planning / MPC stage up inside the project
# container: MuJoCo 2.1.2 + mujoco_py (cymj) + headless EGL, then prove it with
# run_scripts/mujoco_smoke.py.
#
# Training (`train.py`) needs NONE of this; it is for `plan.py` / `run_mpc.sh`
# and the landscape/figure stage. The script writes ~/mujoco_env.sh (planning-only
# exports, never ~/.bashrc) and then runs the smoke test in the container.
#
# Usage (login node, or inside an srun allocation):
#   bash run_scripts/setup_mujoco_server.sh                 # write env + build cymj + smoke (WRITABLE overlay)
#   bash run_scripts/setup_mujoco_server.sh --check         # read-only overlay (use while training holds it rw)
#   bash run_scripts/setup_mujoco_server.sh --no-smoke      # only (re)write ~/mujoco_env.sh
#   MUJOCO_LD_MODE=prepend bash run_scripts/setup_mujoco_server.sh   # if the loader cannot find libmujoco210.so
#
# Why writable: mujoco_py compiles its `cymj` Cython extension on first import
# into site-packages INSIDE the overlay, so the first import needs write access.
# A running training job holds that overlay read-write, which is what --check is
# for (it works once cymj exists). Anything that imports the sim also needs
# MUJOCO_GL=egl on a headless node -- nothing in the repo sets it for planning.
# =============================================================================
set -euo pipefail

# sbatch spools a copy of the script, so $BASH_SOURCE is useless there: prefer the
# submission dir, then this script's dir, then $PWD (see mpc_server.sh).
REPO="${REPO_HOST:-}"
if [ -z "$REPO" ]; then
    for _cand in "${SLURM_SUBMIT_DIR:-}" "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." 2>/dev/null && pwd)" "$PWD"; do
        if [ -n "$_cand" ] && [ -d "$_cand/run_scripts" ]; then REPO="$_cand"; break; fi
    done
    unset _cand
fi
SIF="${SIF:-/share/apps/images/cuda12.1.1-cudnn8.9.0-devel-ubuntu22.04.2.sif}"
SCRATCH="${SCRATCH:-/scratch/akn7847}"
OVERLAY="${OVERLAY:-$SCRATCH/containers/temporal-straightening/overlay-50G-10M.ext3}"
REPO_IN_CONTAINER="${REPO_IN_CONTAINER:-/home/akn7847/wm/temporal-straightening-PL}"
MUJOCO_DIR="${MUJOCO_DIR:-$HOME/.mujoco/mujoco210}"
ENV_FILE="${ENV_FILE:-$HOME/mujoco_env.sh}"
CONDA_ENV="${CONDA_ENV:-/opt/miniconda/envs/ts}"
MUJOCO_LD_MODE="${MUJOCO_LD_MODE:-append}"
CKPT_ROOT="${CKPT_ROOT:-$SCRATCH/datasets/worldmodelcheckpoints}"
# Data layout, shared with training/planning (one place: run_scripts/dataset_paths.sh).
source "$REPO/run_scripts/dataset_paths.sh"
DATA_ROOT="${DATA_ROOT:-$DATA_ROOT}"
FIX_SCRIPT="${FIX_SCRIPT:-$HOME/.ts_fix_mujoco_py.sh}"   # generated by --fix-mujoco-py

CHECK_ONLY=0
RUN_SMOKE=1
DRY_RUN=0
SMOKE_ARGS=""
FIX_MUJOCO_PY=0
for arg in "$@"; do
    case "$arg" in
        --check)       CHECK_ONLY=1 ;;
        --no-smoke)    RUN_SMOKE=0 ;;
        --dry-run)     DRY_RUN=1 ;;
        --fix-mujoco-py) FIX_MUJOCO_PY=1 ;;
        --data-root=*) DATA_ROOT="${arg#--data-root=}" ;;
        --skip-render) SMOKE_ARGS="--skip-render" ;;
        -h|--help)  sed -n '2,26p' "$0"; exit 0 ;;
        *) echo "unknown flag: $arg" >&2; exit 2 ;;
    esac
done

# --- host-side prerequisites -------------------------------------------------
[ -f "$SIF" ] || { echo "FATAL: container image not found: $SIF" >&2; exit 1; }
[ -f "$OVERLAY" ] || { echo "FATAL: overlay not found: $OVERLAY" >&2; exit 1; }
if [ ! -f "$MUJOCO_DIR/bin/libmujoco210.so" ]; then
    cat >&2 <<EOF
FATAL: MuJoCo 2.1.2 not found under $MUJOCO_DIR
  mkdir -p "\$HOME/.mujoco"
  wget https://mujoco.org/download/mujoco210-linux-x86_64.tar.gz -P "\$HOME/.mujoco"
  tar -xzf "\$HOME/.mujoco/mujoco210-linux-x86_64.tar.gz" -C "\$HOME/.mujoco"
  ls "\$HOME/.mujoco/mujoco210/bin"      # want libmujoco210.so + libglew*.so
(An exported MUJOCO_PY_MUJOCO_PATH in one interactive shell is not enough --
 this script and ~/mujoco_env.sh set it for every planning process.)
EOF
    exit 1
fi
[ -d "$REPO/run_scripts" ] || { echo "FATAL: run this from inside the repo ($REPO)" >&2; exit 1; }

# --- ~/mujoco_env.sh: planning-only exports ---------------------------------
cat > "$ENV_FILE" <<EOF
#!/usr/bin/env bash
# Written by run_scripts/setup_mujoco_server.sh -- source it in PLANNING jobs only
# (plan.py / run_mpc.sh / landscape). Do NOT source it before train.py: it puts the
# MuJoCo libs in LD_LIBRARY_PATH, which is the suspected cause of "cannot import
# torch" when they shadow the conda ones (MUJOCO_LD_MODE=append keeps them last).
export MUJOCO_PY_MUJOCO_PATH="\${MUJOCO_PY_MUJOCO_PATH:-$MUJOCO_DIR}"
export MUJOCO_GL="\${MUJOCO_GL:-egl}"                 # headless EGL; unset = glfw/X11
export PYOPENGL_PLATFORM="\${PYOPENGL_PLATFORM:-egl}"
export EGL_GPU="\${EGL_GPU:-0}"                       # PyFleX only; harmless here
export D4RL_SUPPRESS_IMPORT_ERROR="\${D4RL_SUPPRESS_IMPORT_ERROR:-1}"
# PYTHON: discovered at source time. Do not hardcode a prefix -- on NYU Torch the
# ts env is at /opt/conda-envs/ts (not /opt/miniconda/envs/ts).
if [ -z "\${PYTHON:-}" ]; then
    if [ -x "\${CONDA_PREFIX:-}/bin/python" ] && [ "\$(basename \${CONDA_PREFIX:-})" = "ts" ]; then
        export PYTHON="\$CONDA_PREFIX/bin/python"
    else
        for _p in /opt/conda-envs/ts /opt/miniconda/envs/ts "\$HOME/miniconda3/envs/ts"; do
            if [ -x "\$_p/bin/python" ]; then export PYTHON="\$_p/bin/python"; break; fi
        done
        unset _p
    fi
fi
export MUJOCO_LD_MODE="\${MUJOCO_LD_MODE:-$MUJOCO_LD_MODE}"

_mj="\$MUJOCO_PY_MUJOCO_PATH/bin"
# idempotent: drop any earlier copies of the two dirs we manage, then add once
_ld=""; _old_ifs="\$IFS"; IFS=':'
for _d in \${LD_LIBRARY_PATH:-}; do
    case "\$_d" in
        ""|"\$_mj"|"/usr/lib/nvidia") ;;
        *) _ld="\${_ld:+\$_ld:}\$_d" ;;
    esac
done
IFS="\$_old_ifs"
if [ "\$MUJOCO_LD_MODE" = "prepend" ]; then
    export LD_LIBRARY_PATH="\$_mj:/usr/lib/nvidia\${_ld:+:\$_ld}"
else
    export LD_LIBRARY_PATH="\${_ld:+\$_ld:}\$_mj:/usr/lib/nvidia"
fi
unset _mj _ld _d _old_ifs
# Data: plan.py reads $DATASET_DIR/<env> and the three datasets are nested
# differently, so DATASET_DIR is PER ENV -- run_mpc.sh sets it itself from
# these values; for a manual plan.py run use
#   DATASET_DIR="$(dataset_dir_for umaze)"  (dataset_paths.sh is sourced in the repo)
export DATA_ROOT="\${DATA_ROOT:-$DATA_ROOT}"
export CKPT_ROOT="\${CKPT_ROOT:-$CKPT_ROOT}"
EOF
chmod +x "$ENV_FILE"
echo "wrote $ENV_FILE   (MUJOCO_LD_MODE=$MUJOCO_LD_MODE, MUJOCO_GL=egl, PYTHON discovered at source time)"

# --- run the smoke test inside the container ---------------------------------
# --bind home: apptainer binds the *current working directory* by default, so the repo
# is visible inside the container while a file written next to it (such as
# ~/mujoco_env.sh) is NOT, and sourcing it fails with "No such file or directory".
# Add the same flag to your own interactive / slurm container runs.
# There is no read-only variant of this stack: mujoco_py takes a write lock
# (fasteners.InterProcessLock) next to cymj*.so on *every* `import mujoco_py`, before it
# checks whether cymj is already built, so a ':ro' overlay fails at that import even when
# nothing needs compiling. --check therefore mounts the overlay read-write as well; the
# only thing it changes is that --fix-mujoco-py is refused.
MOUNT=(--fakeroot --nv --bind "$HOME:$HOME" --overlay "$OVERLAY")
if [ "$CHECK_ONLY" = "1" ]; then
    echo "  (--check: smoke test only; the overlay is read-write, as every run needs)"
fi

echo
echo "=== container : $SIF"
echo "=== overlay   : $OVERLAY (read-write: mujoco_py takes a write lock on every import)"
echo "=== env file  : $ENV_FILE"
echo "=== repo      : $REPO_IN_CONTAINER"

write_fix_script() {
    cat > "$FIX_SCRIPT" <<'FIXEOF'
#!/usr/bin/env bash
# Generated by run_scripts/setup_mujoco_server.sh --fix-mujoco-py. Runs INSIDE the
# project container; nothing here is expanded by the host. $1 = repo in container.
set -uo pipefail
export PATH=/opt/miniconda/bin:$PATH
source /opt/miniconda/etc/profile.d/conda.sh
conda activate ts
REPO_IN_CONTAINER="${1:?repo path required}"
PYTHON="$(command -v python)"
PYSP="$("$PYTHON" -c 'import site; print(site.getsitepackages()[0])')"
MJ="$PYSP/mujoco_py"
echo "[fix] python : $PYTHON"
echo "[fix] gcc    : $(gcc -dumpversion 2>/dev/null || echo 'gcc not on PATH')"
echo "[fix] Cython : $("$PYTHON" -c 'import Cython; print(Cython.__version__)' 2>/dev/null || echo MISSING)"

# 1. Cython pin: mujoco-py 2.1.2.14 predates Cython 3 (environment.yaml pins 0.29.37).
"$PYTHON" -m pip install --no-cache-dir "cython==0.29.37" || exit 1

# 2. mujoco_py/generated/ holds SHIPPED SOURCES (__init__.py, const.py, and wrappers.pxi
#    which cymj.pyx includes) -- never `rm -rf` that directory.
for f in __init__.py const.py wrappers.pxi; do
    if [ ! -f "$MJ/generated/$f" ]; then
        echo "[fix] MISSING $MJ/generated/$f"
        echo "[fix]   restore: $PYTHON -m pip install --no-cache-dir --force-reinstall --no-deps mujoco-py==2.1.2.14"
        exit 1
    fi
done

# 3. GCC>=14 compile flags + GPU/EGL builder + an existing driver-lib dir (idempotent).
"$PYTHON" "$REPO_IN_CONTAINER/run_scripts/patch_mujoco_py.py" || exit 1

# 4. Clean ONLY build artifacts, then rebuild (the first import compiles cymj).
rm -f "$MJ/cymj.c"
rm -rf "$MJ/generated/_pyxbld_"*
"$PYTHON" -c "import mujoco_py, mujoco_py.cymj as c; print('[fix] built', mujoco_py.__version__, c.__file__)" || exit 1
echo "[fix] done -- now run: bash run_scripts/setup_mujoco_server.sh"
FIXEOF
    chmod +x "$FIX_SCRIPT"
}

if [ "$FIX_MUJOCO_PY" = "1" ]; then
    if [ "$CHECK_ONLY" = "1" ]; then
        echo "FATAL: --fix-mujoco-py needs a WRITABLE overlay; drop --check." >&2
        exit 2
    fi
    write_fix_script
    echo "wrote $FIX_SCRIPT"
    if [ "$DRY_RUN" = "1" ]; then
        echo "--dry-run: apptainer exec ${MOUNT[*]} $SIF bash -lc 'bash $FIX_SCRIPT <repo-in-container>'"
        sed -n "1,200p" "$FIX_SCRIPT"
        exit 0
    fi
    apptainer exec "${MOUNT[@]}" "$SIF" bash -lc "bash $FIX_SCRIPT $REPO_IN_CONTAINER"
    rc=$?
    [ "$rc" -eq 0 ] || { echo "FATAL: --fix-mujoco-py failed (exit $rc)." >&2; exit "$rc"; }
elif [ "$RUN_SMOKE" = "1" ]; then
    set +e
    CONTAINER_SCRIPT="
        set -euo pipefail
        [ -r "$ENV_FILE" ] || { echo 'FATAL: the env file is not visible inside the container: mount your home dir with --bind (SERVER_CONTEXT 11.1)' >&2; exit 9; }
        export PATH=/opt/miniconda/bin:\$PATH
        source /opt/miniconda/etc/profile.d/conda.sh
        conda activate ts
        export PYTHON=\$(command -v python)   # discovered inside the container
        source $ENV_FILE
        cd $REPO_IN_CONTAINER
        export PYTHONPATH=\$PWD\${PYTHONPATH:+:\$PYTHONPATH}
        python -c 'import sys; print(\"[container] python\", sys.executable)'
        python run_scripts/mujoco_smoke.py $SMOKE_ARGS
    "
    if [ "$DRY_RUN" = "1" ]; then
        echo "--dry-run: apptainer exec ${MOUNT[*]} $SIF bash -lc <script below>"
        printf '%s\n' "$CONTAINER_SCRIPT"
        exit 0
    fi
    apptainer exec "${MOUNT[@]}" "$SIF" bash -lc "$CONTAINER_SCRIPT"
    rc=$?
    set -e
    if [ "$rc" -ne 0 ]; then
        echo "FATAL: the in-container smoke test failed (exit $rc)." >&2
        echo "       Fix the FAIL stages printed above, then re-run this script." >&2
        exit "$rc"
    fi
else
    echo "  (--no-smoke: skipping the container run)"
fi

cat <<EOF

next: the planning / MPC stage can run here. Validation pass, then the real MPC:

  source $ENV_FILE                 # planning-only env (MuJoCo + EGL)
  # if mujoco_py ever breaks: bash run_scripts/setup_mujoco_server.sh --fix-mujoco-py
  # in YOUR OWN container runs, bind your home so that file is visible:
  #   apptainer exec --fakeroot --nv --bind $HOME:$HOME --overlay $OVERLAY $SIF bash -lc '...'
  cd $REPO_IN_CONTAINER
  export PYTHONPATH=\$PWD
  FULL=0 bash run_scripts/run_mpc.sh umaze False gd_mpc --ckpt $CKPT_ROOT/test --seeds 100
  FULL=1 bash run_scripts/run_mpc.sh umaze False gd_mpc --ckpt $CKPT_ROOT/test --seeds 100

  (FULL=0 = run_mpc.sh's validation mode: OOM check + runtime estimate. Add
   'all' as the variant argument to cover all four arms, and OL=1 for open loop.)

results : plan_outputs_gd_mpc/<model>_s100_gH25/  (logs.json, plan.log, plan_targets.pkl)
summary : plan_outputs_gd_mpc/summaries/<model>_gH25.json
tables  : python analysis/div_emb_tables.py   (needs those summaries)
See SERVER_CONTEXT.md, section 'MPC / planning stage', for the failure / fix table.
EOF
